{
  "hash": "f06c193df3c2fe861c277f56acb87e86",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Chapter 4: Geocentric Models\"\ndate: 2022-12-09\n---\n\n\n\n\nThis chapter discusses basic Bayesian model fitting with grid and quadratic approximations. The title, \"geocentric models,\" refers to models that make good predictions, but do not provide causal information about a question. One of these examples is linear regression. This chapter gives examples of basic bayesian linear regression and includes details such as prior predictive checks and how to fit curves with polynomials and b-splines.\n\n## Chapter notes\n\n* Normal distributions arise from sums of random fluctuations. Lognormal distributions arise from products of random fluctuations. This property explains why normal distributions are so good at modeling real world data (ontological justification).\n* Normal distributions can also be justified by the principle of maximum entropy -- if all we are willing to specify about a distribution is its mean and variance, then the normal distribution contains the least amount of information (epistemological justification).\n* Index coding (as opposed to dummy coding or similar methods) makes specification of priors for categorical variables easier.\n* The **prior predictive simulation**, drawing samples from the distribution implied by the priors, is essential for ensuring that our priors are reasonable. Note that we should not compare the prior predictive simulation to the observed data, only to our preexisting knowledge of constraints on the model.\n* Many models which are written in the \"plus epsilon\" form (see pg 81) (typical for linear models) can be rewritten in this more general framework, which will be easier for non-Gaussian models.\n* **Quadratic approximation**, estimating the peak of the posterior distribution with a multivariate normal distribution, is easier than grid approximation and works well when the posterior is approximately Gaussian (many simple examples are). The peak of the quadratic approximate posterior is the *maximum a posteriori* estimate.\n* Recall that even though grid and quadratic approximate posteriors provide an actual estimate of the posterior distribution, we can (and should) still sample from the posterior. This mimics the process for inference on more complicated models that must be fit with MCMC algorithms.\n* A **linear model** fits the mean, $\\mu$, of an outcome as a linear function of the predictor variable(s) and some parameters. These models are often *geocentric* -- they provide good answers, but often say nothing about causality.\n* Plotting simulations of the posterior distribution can provide a lot of information about the posterior (see pg 99), often much more than tables of calculations alone.\n* These types of Bayesian models incorporate two different types of uncertainty -- uncertainty in parameter values, which is based on the plausibility of parameter values after seeing the data, and uncertainty from sampling processes.\n* We can extend linear models to fit curved patterns in datas in several ways, but two of the easiest are polynomials and b-splines. Priors can be difficult to fit to both, as these models are also geocentric. They can accurately fit curves, but do not describe the mechanism or process that generates curved data in the first place. See pg. 119 for an example of fitting a b-spline model using `rethinking`. One further extension is the generalized additive model (GAM) which incorporates smoothing over continuous predictor variables.\n\n## Exercises\n\nThe first few questions are about the following model.\n\\begin{align*}\ny_i &\\sim \\mathrm{Normal}(\\mu, \\sigma) \\\\\n\\mu &\\sim \\mathrm{Normal}(0, 10) \\\\\n\\sigma &\\sim \\mathrm{Exponential}(1)\n\\end{align*}\n\n### 4E1\nIn the model shown, the line $y_i \\sim \\mathrm{Normal}(\\mu, \\sigma)$ is the likelihood.\n\n### 4E2\nThe model contains two parameters ($\\mu$ and $\\sigma$).\n\n### 4E3\nTo use Bayes' theorem to calculate the posterior, we would write\n$$\n\\frac{\\prod_{i} \\mathrm{Normal}(y_i \\mid \\mu, \\sigma) \\times \\mathrm{Normal}(\\mu \\mid 0, 10) \\times \\mathrm{Exponential}(\\sigma \\mid 1)}{\\int\\int \\prod_{i} \\mathrm{Normal}(y_i \\mid \\mu, \\sigma) \\times \\mathrm{Normal}(\\mu \\mid 0, 10) \\times \\mathrm{Exponential}(\\sigma \\mid 1) \\ \\mathrm{d}\\mu \\ \\mathrm{d}\\sigma}.\n$$\n\n### 4E4\nIn the model shown below, the linear model is the line $\\mu_i = \\alpha + \\beta x_i$.\n\\begin{align*}\ny_i &\\sim \\mathrm{Normal}(\\mu, \\sigma) \\\\\n\\mu_i &= \\alpha + \\beta x_i \\\\\n\\alpha &\\sim \\mathrm{Normal}(0, 10) \\\\\n\\beta &\\sim \\mathrm{Normal}(0, 1) \\\\\n\\sigma &\\sim \\mathrm{Exponential}(2)\n\\end{align*}\n\n### 4E5\nThere are three parameters in the posterior distribution of the model shown ($\\alpha$, $\\beta$, and $\\sigma$) -- $\\mu$ is no longer a parameter of the model since it is calculated deterministically.\n\n### 4M1\nFor the model definition below, simulate observed $y$ values from the prior.\n\\begin{align*}\ny_i &\\sim \\mathrm{Normal}(\\mu, \\sigma) \\\\\n\\mu &\\sim \\mathrm{Normal}(0, 10) \\\\\n\\sigma &\\sim \\mathrm{Exponential}(1)\n\\end{align*}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Do the simulation\nmu <- rnorm(1000, mean = 0, sd = 10)\nsigma <- rexp(1000, rate = 1)\ny <- rnorm(1000, mu, sigma)\n\n# Plot the results\nlayout(matrix(c(1, 2, 3), ncol = 3))\nhist(y, breaks = \"FD\", main = \"y\")\nhist(mu, breaks = \"FD\", main = \"mu\")\nhist(sigma, breaks = \"FD\", main = \"sigma\")\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/4M1-1.png){width=100%}\n:::\n:::\n\n\n\n\n### 4M2\nTranslate the model into a `quap` formula.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny ~ dnorm(mu, sigma),\nmu ~ dnorm(0, 10),\nsigma ~ dexp(1)\n```\n:::\n\n\n\n\n### 4M3\nTranslate the `quap` model formula below into a mathematical model definition.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny ~ dnorm(mu, sigma),\nmu <- a + b * x,\na ~ dnorm(0, 10),\nb ~ dunif(0, 1),\nsigma ~ dexp(1)\n```\n:::\n\n\n\n\n\\begin{align*}\ny_i &\\sim \\mathrm{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i &= a + b * x_i \\\\\na &\\sim \\mathrm{Normal}(0, 10) \\\\\nb &\\sim \\mathrm{Uniform}(0, 1) \\\\\n\\sigma &\\sim \\mathrm{Exponential}(1)\n\\end{align*}\n\n### 4M4\nA sample of students is measured for height each year for 3 years. After the third year, you want to fit a linear regression predicting height using year as a predictor. Write down the mathematical model, defending any priors you choose.\n\n\\begin{align*}\ny_i &\\sim \\mathrm{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i &= \\alpha + \\beta * (\\mathrm{year}_i - \\min \\mathrm{year}_i) \\\\\n\\alpha &\\sim \\mathrm{Normal}(120, 30) \\\\\n\\beta &\\sim \\mathrm{Log-Normal}(0, 1.5) \\\\\n\\sigma &\\sim \\mathrm{Exponential}(0, 0.2)\n\\end{align*}\n\nTo create the priors, I assumed that height was measured in centimeters. If it is not, transforming either the data or the prior coefficients is a simple linear transformation. The prior for the intercept is centered at a relatively small height (around four feet) with a large spread to allow for differences in biological sex or age distributions in the population, since these were not specified in the question. I subtracted the minimum year in the model so that the years would be scaled as 0, 1, 2, 3, instead of the actual numeric value of the year.\n\nIn general, we know that height increases over time, so I used a lognormal prior for the slope to enforce a positivity constraint. The prior has a location parameter of 0, allowing for the chance of no growth over the three years, but a wide spread was chosen by experimenting until the prior predictive simulation represented a wide range of possible trajectories with very few trajectories appearing to be biologically unreasonable. Again, the value was chosen by experimenting with prior predictive simulations until the result appeared to capture a large variety of biologically meaningful trajectories.\n\nI assigned an exponential prior to sigma to reflect the fact that all variances are positive, and most tend to be small-ish, but can be large. I had a difficult time with this one in particular because this model structure seems to imply that people can shrink in-between years. This would be possible with measurement error, but I think it would be quite difficult to have measurement error this severe in something like height, which is easy to measure. However, in order to include a constraint that height can only increase, I think we would need to change the likelihood in the model, which we haven't discussed yet in the book, so I didn't want to worry about that. (For example, we could make height lognormally distributed, so random fluctuations would only increase height, as opposed to the current model where random fluctuations can decrease height.)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n\n# Prior predictive simulation\na <- rnorm(1000, 120, 30)\nb <- rlnorm(1000, 0, 1.5)\n\n# PPS for mu -- only needs a and b\nlayout(matrix(c(1, 2), nrow = 1))\nplot(\n\tNULL,\n\txlim = c(-0.05, 3.05),\n\tylim = c(-100, 400),\n\txlab = c(\"year\"),\n\tylab = c(\"height\"),\n\tmain = \"prior predictive simulation of mu\"\n)\nabline(h = 0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\nfor (i in 1:1000) {\n\tcurve(a[i] + b[i] * x, from = 0, to = 3, add = TRUE,\n\t\t  col = rethinking::col.alpha(\"black\", 0.1))\n}\n\n# PPS for y -- for each a, b, simulate variance around the sampled mu.\nplot(\n\tNULL,\n\txlim = c(-0.05, 3.05),\n\tylim = c(-100, 400),\n\txlab = c(\"year\"),\n\tylab = c(\"height\"),\n\tmain = \"prior predictive simulation of y\"\n)\nabline(h = 0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\nsigma <- rexp(1000, 1 / 5)\nfor (i in 1:1000) {\n\tlines(x = 0:3, y = rnorm(4, a[i] + b[i] * 0:3, sigma[i]),\n\t\t  col = rethinking::col.alpha(\"black\", 0.1))\n}\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/4M4-1.png){width=100%}\n:::\n:::\n\n\n\n\n### 4M5\nIf I were reminded that every student got taller each year, this would not really change my choice of priors, but it does make me consider the same issues. I already accounted for this in the prior for $\\beta$. However, it does make me think more about the likelihood I used -- I really dislike that this likelihood allows for fluctuations that show up like this. Height is not measured perfectly, but large variations are uncommon. So perhaps it makes more sense to have quite a small variance parameter ($\\sigma$). Or perhaps we could structure the model so that each student has a common variance parameter that does not change every year. We could also consider making the effect of $\\beta$ stronger, so that there is an assumed growth effect and not growing each year is more rare. So perhaps we could consider the following adjusted priors.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n\n# Prior predictive simulation\na <- rnorm(1000, 120, 30)\nb <- rlnorm(1000, 2, 0.5)\n\n# PPS for mu -- only needs a and b\nlayout(matrix(c(1, 2), nrow = 1))\nplot(\n\tNULL,\n\txlim = c(-0.05, 3.05),\n\tylim = c(-100, 400),\n\txlab = c(\"year\"),\n\tylab = c(\"height\"),\n\tmain = \"prior predictive simulation of mu\"\n)\nabline(h = 0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\nfor (i in 1:1000) {\n\tcurve(a[i] + b[i] * x, from = 0, to = 3, add = TRUE,\n\t\t  col = rethinking::col.alpha(\"black\", 0.1))\n}\n\n# PPS for y -- for each a, b, simulate variance around the sampled mu.\nplot(\n\tNULL,\n\txlim = c(-0.05, 3.05),\n\tylim = c(-100, 400),\n\txlab = c(\"year\"),\n\tylab = c(\"height\"),\n\tmain = \"prior predictive simulation of y\"\n)\nabline(h = 0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\nsigma <- rexp(1000, 1)\nfor (i in 1:1000) {\n\tlines(x = 0:3, y = rnorm(4, a[i] + b[i] * 0:3, sigma[i]),\n\t\t  col = rethinking::col.alpha(\"black\", 0.1))\n}\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/4M5-1.png){width=100%}\n:::\n:::\n\n\n\n\nThese priors still represent a wide range of biologically accurate values, but there is much less internal (within-subject) fluctuation in height between years, and on average, the slope is steeper.\n\n### 4M6\nIf I had the information that variance among heights for students of the same age is never more than 64cm, this would change my choice of variance prior (assuming that this is *a priori* information and not measured from our sample). If this were measured from the sample, I would not change my priors. But we could consider changing the prior for $\\sigma$ like so. Using the empirical rule for normal distributions, I reasoned that 21 is a reasonable constraint for an upper bound on a Uniform prior for sigma -- the resultant likelihood will have approximately 99% of observations within $3 \\times 21 = 63$ cm of the mean.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n\n# Prior predictive simulation\na <- rnorm(1000, 120, 30)\nb <- rlnorm(1000, 2, 0.5)\n\n# PPS for mu -- only needs a and b\nlayout(matrix(c(1, 2), nrow = 1))\nplot(\n\tNULL,\n\txlim = c(-0.05, 3.05),\n\tylim = c(-100, 400),\n\txlab = c(\"year\"),\n\tylab = c(\"height\"),\n\tmain = \"prior predictive simulation of mu\"\n)\nabline(h = 0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\nfor (i in 1:1000) {\n\tcurve(a[i] + b[i] * x, from = 0, to = 3, add = TRUE,\n\t\t  col = rethinking::col.alpha(\"black\", 0.1))\n}\n\n# PPS for y -- for each a, b, simulate variance around the sampled mu.\nplot(\n\tNULL,\n\txlim = c(-0.05, 3.05),\n\tylim = c(-100, 400),\n\txlab = c(\"year\"),\n\tylab = c(\"height\"),\n\tmain = \"prior predictive simulation of y\"\n)\nabline(h = 0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\nsigma <- runif(1000, 0, 21)\nfor (i in 1:1000) {\n\tlines(x = 0:3, y = rnorm(4, a[i] + b[i] * 0:3, sigma[i]),\n\t\t  col = rethinking::col.alpha(\"black\", 0.1))\n}\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/4M6-1.png){width=100%}\n:::\n:::\n\n\n\n\nThis variance is quite large, which I think intensifies the problem I was previously discussing. Since we consider each annual measurement to be independent, without any \"clustering\" (we haven't used that word yet so I don't want to use it wrong) by inviduals, following this model to the letter allows for wide fluctuations within the predicted trajectory -- to me it just doesn't make sense for the simulated trajectory to be lower in year $N + 1$ than in year $N$.\n\n### 4M7\nRefit model `m4.3` but omit the mean weight `xbar`. Compare the new model's posterior to that or the original model, then compare the posterior predictions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\nlibrary(rethinking)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: cmdstanr\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis is cmdstanr version 0.8.1.9000\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n- CmdStanR documentation and vignettes: mc-stan.org/cmdstanr\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n- CmdStan path: C:/Users/Zane/.cmdstan/cmdstan-2.34.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n- CmdStan version: 2.34.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nA newer version of CmdStan is available. See ?install_cmdstan() to install it.\nTo disable this check set option or environment variable cmdstanr_no_ver_check=TRUE.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: posterior\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis is posterior version 1.6.0\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'posterior'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    mad, sd, var\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    %in%, match\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: parallel\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrethinking (Version 2.40)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'rethinking'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:stats':\n\n    rstudent\n```\n\n\n:::\n\n```{.r .cell-code}\ndata(Howell1)\nd <- Howell1\nd2 <- d[d$age >= 18, ]\nm_4m7 <-\n\tquap(\n\t\tflist = alist(\n\t\t\theight ~ dnorm(mu, sigma),\n\t\t\tmu <- a + b * weight,\n\t\t\ta ~ dnorm(178, 20),\n\t\t\tb ~ dlnorm(0, 1),\n\t\t\tsigma ~ dunif(0, 50)\n\t\t),\n\t\tdata = d2\n\t)\n```\n:::\n\n\n\n\nFirst we'll look at the posterior summary.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecis(m_4m7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             mean         sd        5.5%       94.5%\na     114.5302928 1.89715027 111.4982802 117.5623053\nb       0.8908259 0.04174484   0.8241096   0.9575422\nsigma   5.0711281 0.19109884   4.7657152   5.3765409\n```\n\n\n:::\n:::\n\n\n\n\nThe intercept estimate is quite different -- the previous model reported the following statistics for a: mean 154.6, sd 0.27, 5.5% 154.17, 94.5% 155.05. So our parameter is much smaller with a larger variance. However, the estimates for b and sigma are almost exactly the same as the estimates given for the previous model (see book pg 99). In particular, we should look at the covariance matrix according to the question.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcov(m_4m7) |> round(digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           a      b sigma\na      3.599 -0.078 0.009\nb     -0.078  0.002 0.000\nsigma  0.009  0.000 0.037\n```\n\n\n:::\n:::\n\n\n\n\nThe variance for a is much higher, while the variance for b and sigma is exactly the same as the book reports. However, there is now some covariance between a and b, and between a and sigma (but not between b and sigma). Next I'll plot a sample of prior predictions. Since the uncertainty is so narrow, I decided to only plot 100 posterior samples. The red line shows the maximum *a posteriori* estimate.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost <- extract.samples(m_4m7, n = 100)\nlayout(1)\nplot(\n\tx = d2$weight, y = d2$height,\n\txlim = range(d2$weight),\n\tylim = range(d2$height),\n\tcol = rangi2,\n\txlab = \"weight\", ylab = \"height\"\n)\nmtext(\"Sampled posterior predictions\")\n\n# Plot the lines\nfor (i in 1:length(post$a)) {\n\tcurve(post$a[i] + post$b[i] * x,\n\t\t\t\tcol = col.alpha(\"black\", 0.1),\n\t\t\t\tadd = TRUE)\n}\n\nabline(\n\ta = mean(post$a),\n\tb = mean(post$b),\n\tcol = \"red\",\n\tlty = 2\n)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\nThe posterior predictions look about the same to me. So I guess that even when we use different parametrizations (thus changing the interpretation and scale of our alpha parameter), the predictions still work out to be about the same. I think this is foreshadowing MCMC convergence diagnostics with different parametrizations in the future.\n\n### 4M8\nRefit the cherry blossom spline and experiment with changing the number of knots and the width of the prior on the weights. What do you think the combination of these controls?\n\nFirst we'll just refit the example.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data import\ndata(\"cherry_blossoms\")\nd <- cherry_blossoms\nd2 <- d[complete.cases(d$doy), ]\n\nset.seed(100)\n# Create the splits\nnk <- 15\nknot_list <- quantile(d2$year, probs = seq(0, 1, length.out = nk))\nB <- splines::bs(\n\t\t\t\tx = d2$year,\n\t\t\t\t# I think we are recreating the default knots and could set\n\t\t\t\t# df = 13 instead, but nonetheless we persist\n\t\t\t\tknots = knot_list[-c(1, nk)],\n\t\t\t\tdegree = 3,\n\t\t\t\tintercept = TRUE\n\t\t\t)\n\n# Fit the model\nm1 <-\n\tquap(\n\t\tflist = alist(\n\t\t\tD ~ dnorm(mu, sigma),\n\t\t\tmu <- a + B %*% w,\n\t\t\ta ~ dnorm(100, 10),\n\t\t\tw ~ dnorm(0, 10),\n\t\t\tsigma ~ dexp(1)\n\t\t),\n\t\tdata = list(D = d2$doy,\tB = B),\n\t\tstart = list(w = rep(0, ncol(B)))\n\t)\n\n# Get the posterior predictions and plot them\nmu <- link(m1)\nmu_PI <- apply(mu, 2, PI, 0.97)\nplot(d2$year, d2$doy, col = col.alpha(rangi2, 0.3), pch = 16,\n\t\t xlab = \"year\", ylab = \"Day in year\",\n\t\t main = \"Original model\")\nshade(mu_PI, d2$year, col = col.alpha(\"darkgray\", 0.5))\nlines(d2$year, y = apply(mu, 2, mean), col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\nNow let's fit an example with more knots, say 30. This is a dramatic increase but I really want to see the effect.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n# Create the splits\nnk <- 30\nknot_list <- quantile(d2$year, probs = seq(0, 1, length.out = nk))\nB <- splines::bs(\n\t\t\t\tx = d2$year,\n\t\t\t\t# I think we are recreating the default knots and could set\n\t\t\t\t# df = 13 instead, but nonetheless we persist\n\t\t\t\tknots = knot_list[-c(1, nk)],\n\t\t\t\tdegree = 3,\n\t\t\t\tintercept = TRUE\n\t\t\t)\n\n# Fit the model\nm2 <-\n\tquap(\n\t\tflist = alist(\n\t\t\tD ~ dnorm(mu, sigma),\n\t\t\tmu <- a + B %*% w,\n\t\t\ta ~ dnorm(100, 10),\n\t\t\tw ~ dnorm(0, 10),\n\t\t\tsigma ~ dexp(1)\n\t\t),\n\t\tdata = list(D = d2$doy,\tB = B),\n\t\tstart = list(w = rep(0, ncol(B)))\n\t)\n\n# Get the posterior predictions and plot them\nmu <- link(m2)\nmu_PI <- apply(mu, 2, PI, 0.97)\nplot(d2$year, d2$doy, col = col.alpha(rangi2, 0.3), pch = 16,\n\t\t xlab = \"year\", ylab = \"Day in year\",\n\t\t main = \"More knots\")\nshade(mu_PI, d2$year, col = col.alpha(\"darkgray\", 0.5))\nlines(d2$year, y = apply(mu, 2, mean), col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nNow we'll also increase the width of the prior for $w$. Again, I'll increase this dramatically to make the effect easier to see.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\n# Create the splits\nnk <- 20\nknot_list <- quantile(d2$year, probs = seq(0, 1, length.out = nk))\nB <- splines::bs(\n\t\t\t\tx = d2$year,\n\t\t\t\t# I think we are recreating the default knots and could set\n\t\t\t\t# df = 13 instead, but nonetheless we persist\n\t\t\t\tknots = knot_list[-c(1, nk)],\n\t\t\t\tdegree = 3,\n\t\t\t\tintercept = TRUE\n\t\t\t)\n\n# Fit the model\nm3 <-\n\tquap(\n\t\tflist = alist(\n\t\t\tD ~ dnorm(mu, sigma),\n\t\t\tmu <- a + B %*% w,\n\t\t\ta ~ dnorm(100, 10),\n\t\t\tw ~ dnorm(0, 70),\n\t\t\tsigma ~ dexp(1)\n\t\t),\n\t\tdata = list(D = d2$doy,\tB = B),\n\t\tstart = list(w = rep(0, ncol(B)))\n\t)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCaution, model may not have converged.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCode 1: Maximum iterations reached.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Get the posterior predictions and plot them\nmu <- link(m3)\nmu_PI <- apply(mu, 2, PI, 0.97)\nplot(d2$year, d2$doy, col = col.alpha(rangi2, 0.3), pch = 16,\n\t\t xlab = \"year\", ylab = \"Day in year\",\n\t\t main = \"More knots and wider prior\")\nshade(mu_PI, d2$year, col = col.alpha(\"darkgray\", 0.5))\nlines(d2$year, y = apply(mu, 2, mean), col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\nHmm, it's hard to see a difference. Let's try plotting the three lines on top of each other.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlayout(1)\nplot(\n\tx = d2$year, y = d2$doy,\n\txlab = \"year\", ylab = \"Day in year\",\n\txlim = range(d2$year), ylim = range(d2$doy),\n\tcol = col.alpha(rangi2, 0.3), pch = 16\n)\nlines(d2$year, y = apply(link(m1), 2, mean), col = \"black\")\nlines(d2$year, y = apply(link(m2), 2, mean), col = \"blue\")\nlines(d2$year, y = apply(link(m3), 2, mean), col = \"red\")\nlegend(\n\tx = \"top\",\n\tc(\"original\", \"more knots\", \"more knots and wider prior\"),\n\tcol = c(\"black\", \"blue\", \"red\"),\n\tlty = c(1, 1, 1)\n)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-10-1.png){width=100%}\n:::\n:::\n\n\n\n\nYep, from this plot the difference is pretty easy to see. The number of knots and the prior for the weights controls the \"wiggliness\" (the smoothness or penalty) of the splines. More knots or a wider prior allows for more local variation in the spline curve, whereas constraining the number of knots (or shrinking the weights toward 0) constrains the spline, forcing it to vary less. I guess that the prior on the weights here is equivalent to increasing the penalty term of some other kind of spline, and a higher number of knots allows for a higher degree of interpolation as more inflection points are included.\n\n### 4H1\nWe want to estimate the expected heights of the 5 individuals from the !Kung census with weights given in the text. Since we already saw that the predictions from our fitted model earlier were the same as the predictions in the book, I'll use that model to do this. All we need to do is create a data frame with the heights of these individuals and pass it to `link` with the model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the data for the new individuals\nnew_indiv <-\n\ttibble::tribble(\n\t\t~individual, ~weight,\n\t\t1, 46.95,\n\t\t2, 43.72,\n\t\t3, 64.78,\n\t\t4, 32.59,\n\t\t5, 54.63\n\t)\n\n# Get the samples from the posterior at the given weights\npreds <- rethinking::link(fit = m_4m7, data = new_indiv)\n\n# Get the means and round it\nnew_indiv$means <- apply(preds, 2, function(x) round(mean(x), 2))\n\n# Calculate the PI and format it\nPIs <- apply(preds, 2, PI, 0.89)\nnew_indiv$PIs <- apply(PIs, 2, function(x) paste0(round(x, 2), collapse = \", \"))\n\n# Format names and create the table\nnames(new_indiv) <- c(\"Individial\", \"weight\", \"expected height\", \"89% interval\")\nknitr::kable(\n\tnew_indiv,\n\tcaption = paste0(\"Expected heights with 89% equal-tailed posterior intervals\",\n\t\t\t\t\t\t\t\t\t \" for the five individuals wiuthout recorded heights in the\",\n\t\t\t\t\t\t\t\t\t \" !Kung census data, using link.\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Expected heights with 89% equal-tailed posterior intervals for the five individuals wiuthout recorded heights in the !Kung census data, using link.\n\n| Individial| weight| expected height|89% interval   |\n|----------:|------:|---------------:|:--------------|\n|          1|  46.95|          156.35|155.88, 156.77 |\n|          2|  43.72|          153.47|153.04, 153.92 |\n|          3|  64.78|          172.21|170.85, 173.53 |\n|          4|  32.59|          143.57|142.62, 144.51 |\n|          5|  54.63|          163.18|162.4, 163.89  |\n\n\n:::\n:::\n\n\n\n\nAfter talking to my colleague [Juliana](https://jtaube.github.io/), I also decided\nto rerun this using `sim()` -- with predicted heights that include variance from\nthe mean. I think this is probably \"more correct\" so credit to Juliana for\npointing that out to me.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_indiv <-\n\ttibble::tribble(\n\t\t~individual, ~weight,\n\t\t1, 46.95,\n\t\t2, 43.72,\n\t\t3, 64.78,\n\t\t4, 32.59,\n\t\t5, 54.63\n\t)\n# Get the samples from the posterior at the given weights\npreds <- rethinking::sim(fit = m_4m7, data = new_indiv)\n\n# Get the means and round it\nnew_indiv$means <- apply(preds, 2, function(x) round(mean(x), 2))\n\n# Calculate the PI and format it\nPIs <- apply(preds, 2, PI, 0.89)\nnew_indiv$PIs <- apply(PIs, 2, function(x) paste0(round(x, 2), collapse = \", \"))\n\n# Format names and create the table\nnames(new_indiv) <- c(\"Individial\", \"weight\", \"expected height\", \"89% interval\")\nknitr::kable(\n\tnew_indiv,\n\tcaption = paste0(\"Expected heights with 89% equal-tailed posterior intervals\",\n\t\t\t\t\t\t\t\t\t \" for the five individuals wiuthout recorded heights in the\",\n\t\t\t\t\t\t\t\t\t \" !Kung census data, using sim.\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Expected heights with 89% equal-tailed posterior intervals for the five individuals wiuthout recorded heights in the !Kung census data, using sim.\n\n| Individial| weight| expected height|89% interval   |\n|----------:|------:|---------------:|:--------------|\n|          1|  46.95|          156.36|148.29, 164.14 |\n|          2|  43.72|          153.79|145.86, 161.95 |\n|          3|  64.78|          172.15|164.02, 181.17 |\n|          4|  32.59|          143.91|135.7, 152.15  |\n|          5|  54.63|          163.11|154.61, 171.11 |\n\n\n:::\n:::\n\n\n\n\nSo we can see that the results are not that different, but the 89% intervals are a bit wider, which is good. The new intervals incorporate an additional component of the variance that my previous estimates did not, so if I were publishing this model, I would definitely publish the `sim` intervals instead. I guess these are analogous to frequentist prediction intervals as opposed to confidence intervals.\n\n### 4H2\nSelect out all the rows in the `Howell1` data with ages below 18 years of age. Fit a linear regression to these data using `quap`. Present and interpret the estimates. For every 10 units of increase in weight, how much taller does the model predict a child gets?\n\nOk, first we'll subset the data and make a quick plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- Howell1[Howell1$age < 18, ]\nplot(d$weight, d$height, xlab = \"weight\", ylab = \"height\")\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\nd_xbar <- mean(d$weight)\n```\n:::\n\n\n\n\nNow let's fit the model. I'll use the same priors as before, since I already looked at the data. We probably want to actually change the prior on the intercept since children have a lower mean height than adults, but I think it will work out alright.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4h2 <-\n\tquap(\n\t\tflist = alist(\n\t\t\theight ~ dnorm(mu, sigma),\n\t\t\tmu <- a + b * (weight - d_xbar),\n\t\t\ta ~ dnorm(178, 20),\n\t\t\tb ~ dlnorm(0, 1),\n\t\t\tsigma ~ dunif(0, 50)\n\t\t),\n\t\tdata = d\n\t)\nprecis(m4h2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            mean         sd       5.5%      94.5%\na     108.383621 0.60867543 107.410840 109.356402\nb       2.716654 0.06831783   2.607469   2.825839\nsigma   8.437466 0.43060814   7.749271   9.125661\n```\n\n\n:::\n:::\n\n\n\n\nWe can see that the estimate slope is $\\beta = 2.69$. So for every 10 units of increase in weight, our model predicts that a child's height will increase by $26.9$ units.\n\nNext, we'll plot the MAP prediction line with an 89% interval, along with the 89% prediction interval for heights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(d$weight, d$height, xlab = \"weight\", ylab = \"height\")\n\n# Weight values to predict over\nweight_seq <- seq(from = min(d$weight), to = max(d$weight), by = 0.5)\n\n# Get the posterior predictions\nset.seed(100)\nlink_4h2 <- link(m4h2, data = data.frame(weight = weight_seq))\nsim_4h2  <-  sim(m4h2, data = data.frame(weight = weight_seq))\n\n# Summarize the samples\nmu_mean <- apply(link_4h2, 2, mean)\nmu_CI <- apply(link_4h2, 2, PI, 0.89)\nmu_PI <- apply(sim_4h2, 2, PI, 0.89)\n\n# Plot the results -- we want to go backwards, starting with the wider\n# interval first\nshade(mu_PI, weight_seq, col = col.alpha(\"black\", 0.5))\nshade(mu_CI, weight_seq, col = col.alpha(\"lightgray\", 0.75))\nlines(weight_seq, y = mu_mean, col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![The observed height and weight of the children in the !Kung census data (circular points) with the MAP linear regression line (red dashed line), 89% equal-tailed posterior interval of this line (light gray shading), and 89% equal-tailed posterior interval for predicted heights ( dark gray shading).](cp4_files/figure-html/unnamed-chunk-15-1.png){width=100%}\n:::\n:::\n\n\n\n\nThe main issue with the model is that there is clearly some curvature to the trend in the data. There seems to be an inflection point around a weight of 30 where the trend is no longer linear, which will make the entire model fit worse (particularly because this region has high leverage). There is also some curvature in the lower weight values as well. Perhaps it would be better to fit this model with a spline or with a dummy variable for \"age categories\" that interacts with the slope term, allowing the model to \"bend\" at particular points -- the same thing could be accomplished using splines with degree 1. Normally I hate discretization, but in this case these trends are likely to map to our approximate knowledge of human growth. Babies grow faster than toddlers, and teenagers grow faster than younger children. So perhaps including more information in our model could help solve this problem as well. But if we don't want to include age, a spline could probably work better.\n\n### 4H3\nBased on our colleague's suggestion, we want to use the natural logarithm of weight to model height. We'll do that using the entire Howell1 dataset. I'll use the same priors as before.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4h3 <-\n\tquap(\n\t\tflist = alist(\n\t\t\theight ~ dnorm(mu, sigma),\n\t\t\tmu <- a + b * log(weight),\n\t\t\ta ~ dnorm(178, 20),\n\t\t\tb ~ dlnorm(0, 1),\n\t\t\tsigma ~ dunif(0, 50)\n\t\t),\n\t\tdata = Howell1\n\t)\nprecis(m4h3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            mean        sd       5.5%      94.5%\na     -22.874317 1.3342911 -25.006772 -20.741862\nb      46.817789 0.3823240  46.206761  47.428816\nsigma   5.137088 0.1558847   4.887954   5.386222\n```\n\n\n:::\n:::\n\n\n\n\nThese estimates indicate that an individual from the census with mean weight is expected to have a height of $138.27$ units. The slope (b) indicates that for every 1 unit increase in log-weight, height is expected to increase by about 47 units. I think that log-weight units are a bit difficult to think about, this would probably be easier to understand if we'd used log2 or something without an $e$ in it. This coefficient means that if we multiply an individual's weight by $e$ (approximately 2.72), we would expect to see a 47 unit increase in their height. So, e.g., if we used log2, we could interpret this as doubling their weight, but we can't do that now.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the raw data\nplot(height ~ weight, data = Howell1, col = col.alpha(rangi2, 0.5))\n\n# Get the mean and height samples -- I couldn't get sim to work so I did link\n# and then did the sim part myself\nweight_seq <- seq(from = min(Howell1$weight),\n\t\t\t\t\t\t\t\t\tto = max(Howell1$weight),\n\t\t\t\t\t\t\t\t\tby = 1)\nset.seed(100)\nlink_4h3 <- link(m4h3, data = data.frame(weight = weight_seq))\nsim_4h3  <-  sim(m4h3, data = data.frame(weight = weight_seq))\n\n# Summarize the samples\nmu    <- apply(link_4h3, 2, mean)\nmu_CI <- apply(link_4h3, 2, PI, 0.97)\nmu_PI <- apply( sim_4h3, 2, PI, 0.97)\n\n# Add the predictions to the plot\nlines(weight_seq, y = mu_PI[1, ], lty = 2)\nlines(weight_seq, y = mu_PI[2, ], lty = 2)\nshade(mu_CI, weight_seq, col = col.alpha(\"darkgray\", 0.75))\nlines(weight_seq, y = mu, col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\nWell, it does look like our colleague's suggestion produced a better model!\n\n### 4H4\n\nPlot the prior predictive distribution for the parabolic polynomial regression model in the chapter. We want to modify the prior distributions of the parameters so that the prior predictions lie within the reasonable outcome space we defined.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data setup since I keep overwriting names\nd <- Howell1\nd2 <- d[d$age >= 18, ]\n\n# Standardize weight\nd2$weight_s <- scale(d2$weight)\nd2$weight_s2 <- d2$weight_s ^ 2\n\nxbar <- mean(d2$weight)\nsx <- sd(d2$weight)\n\n# Setup\nlayout(matrix(c(1, 2), ncol = 2))\nset.seed(100)\nN <- 100\n\n# Repeat the original priors listed\na <- rnorm(N, 178, 20)\nb1 <- rlnorm(N, 0, 1)\nb2 <- rnorm(N, 0, 1)\n\nplot(\n\tNULL,\n\txlim = range(d2$weight), ylim = c(-100, 400),\n\txlab = \"weight\", ylab = \"height\",\n\tmain = \"Original priors\"\n)\nabline(h =   0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\n\nfor (i in 1:N) {\n\tcurve(\n\t\ta[i] + b1[i] * ((x - xbar) / sx) + b2[i] * (((x - xbar) / sx) ^ 2),\n\t\tfrom = min(d2$weight), to = max(d2$weight),\n\t\tadd = TRUE,\n\t\tcol = col.alpha(\"black\", 0.2)\n\t)\n}\n\n# Repeat the original priors listed\na <- rnorm(N, 178, 20)\nb1 <- rnorm(N, 0, 4)\nb2 <- rnorm(N, 0, 4)\n\nplot(\n\tNULL,\n\txlim = range(d2$weight), ylim = c(-100, 400),\n\txlab = \"weight\", ylab = \"height\",\n\tmain = \"New priors\"\n)\nabline(h =   0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\n\nfor (i in 1:N) {\n\tcurve(\n\t\ta[i] + b1[i] * ((x - xbar) / sx) + b2[i] * (((x - xbar) / sx) ^ 2),\n\t\tfrom = min(d2$weight), to = max(d2$weight),\n\t\tadd = TRUE,\n\t\tcol = col.alpha(\"black\", 0.2)\n\t)\n}\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\nWell, when I looked at the original priors they were all already within the reasonable model space. But since we have a parabola now, we don't need to constrain the linear part to be positive -- we could get an always positive derivative even with a negative linear term ($2ax + b > 0$ for $ax^2 + bx + c$, so e.g. if $a = 2, \\ b = -2$ the derivative will be positive for all $x > 1$, and all of our values are larger than 30). So I changed the priors to get trajectories that cover a bit more of the reasonable space. They approach the edges in some cases, but that's okay. I wasn't really sure what else to do with this question once I saw that the parabolas were all already in the reasonable space.\n\nMaybe I was supposed to NOT standardize the data, even though the chapter did this and the book didn't explicitly say what model to use. However, assigning a biologically meaningful prior without even centering the data is quite difficult, because in this example it makes sense to constrain the (non-centered) intercept at 0 (i.e. a person with weight zero has height zero).\n\nHowever, we can quickly see how this model doesn't make biological sense by thinking about where we should center the data. If we center at the mean, our parabola has to be either concave up or concave down (recall the second derivative of a parabola is constant), which doesn't make any sense. Why would low weight people be taller, or high weight people be shorter? By centering the data at the mean we force the parabola to take one of these two options. So perhaps standardizing by some reference point would be good, but remember that we don't want to look at the data to choose where to standardize. So we're forced to make one of two biologically inaccurate assumptions: either the concavity must be unreasonable or the intercept must be unreasonable. So let's set an unreasonable intercept and choose not to center the data. That way we can at least constrain the concavity to be positive.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Setup\nset.seed(100)\nlayout(matrix(c(1, 2), ncol = 2))\n\n# Repeat the original priors listed\na <- rnorm(N, 178, 20)\nb1 <- rlnorm(N, 0, 1)\nb2 <- rnorm(N, 0, 1)\n\nplot(\n\tNULL,\n\txlim = range(d2$weight), ylim = c(-100, 400),\n\txlab = \"weight\", ylab = \"height\",\n\tmain = \"Original priors\"\n)\nabline(h =   0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\n\nfor (i in 1:N) {\n\tcurve(\n\t\ta[i] + b1[i] * x + b2[i] * (x ^ 2),\n\t\tfrom = min(d2$weight), to = max(d2$weight),\n\t\tadd = TRUE,\n\t\tcol = col.alpha(\"black\", 0.2)\n\t)\n}\n\n# Repeat the original priors listed\na <- rnorm(N, 90, 20)\nb1 <- rnorm(N, 0, 0.5)\nb2 <- rnorm(N, 0.02, 0.005)\n\nplot(\n\tNULL,\n\txlim = range(d2$weight), ylim = c(-100, 400),\n\txlab = \"weight\", ylab = \"height\",\n\tmain = \"New priors\"\n)\nabline(h =   0, lty = 2, lwd = 0.5)\nabline(h = 272, lty = 2, lwd = 0.5)\n\nfor (i in 1:N) {\n\tcurve(\n\t\ta[i] + b1[i] * x + b2[i] * (x ^ 2),\n\t\tfrom = min(d2$weight), to = max(d2$weight),\n\t\tadd = TRUE,\n\t\tcol = col.alpha(\"black\", 0.2)\n\t)\n}\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\nThere. Now our priors for the non-centered data fit inside the reasonable range. Are you happy now? They don't really make any sense (why would a person with 0 weight have 90 height? why do we have to restrain the coefficient for the b terms so much?) but they fit inside the line. I think the better answer for this question is to either standardize the data or avoid using a quadratic model for this problem, which was maybe the entire point of the question.\n\n### 4H5\nReturn to the cherry blossoms data and model the association between blossom date (`doy`) and March temperature (`temp`). Note that there are many missing values in both variables. You may consider a linear model, a polynomial, or a spline on temperature. How well does temperature trend predict the blossom trend?\n\nI'm leaning towards splines for this question -- I expect this relationship to be nonlinear, and given my frustration with polynomial models in the previous question, I think it's okay to stick with a spline. So first we need to set up the splines. We haven't talked about missing data at all yet in this book so I'll just use the complete cases.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"cherry_blossoms\")\nd <- cherry_blossoms[ , c(\"temp\", \"doy\")]\nd2 <- d[complete.cases(d), ]\n```\n:::\n\n\n\n\nLet's do a prior predictive simulation. I'll start with the priors in the book for the previous model, but then adjust if they look unreasonable. I looked at the paper cited in the cherry blossoms data description, and it appears that the temperatures were measured in Kyoto. So I googled \"Kyoto march temperature\" and I guess we can assume that temperatures should be between 3 and 14 degrees celsius. McElreath says that the flowers can bloom any time from March to May, so as long as our predictions are between day 60 (first day of March in regular year) and day 152 (first day of May in leap year), I'll consider that to be \"reasonable\".\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 1000\nset.seed(100)\n\n# Create a range of temperature for the PPS splines\ntemp_range <- seq(2, 14, 0.05)\nnk <- 15\n\n# Create the splines\nB <-\n\tsplines::bs(\n\t\tx = temp_range,\n\t\tknots = quantile(temp_range, probs = seq(0, 1, length.out = nk))[-c(1, nk)],\n\t\tdegree = 3,\n\t\tintercept = TRUE\n\t)\n\n# Simulate a since it is easy\na <- rnorm(N, 100, 10)\n\n# Simulate the weights with a little trickery\nw <- do.call(rbind, purrr::map(1:ncol(B), ~rnorm(N, 0, 15)))\n\n# Calculate the predicted means\nmu <- a + B %*% w\n\n# Plot the pps\nlayout(1)\nplot(\n\tNULL,\n\txlim = c(2, 14), ylim = c(40, 170),\n\txlab = \"temperature (Celsius)\", ylab = \"day of year\",\n\txaxs=\"i\", yaxs=\"i\"\n)\nabline(h =  60, lty = 2, lwd = 0.5)\nabline(h = 152, lty = 2, lwd = 0.5)\n\nfor (i in 1:N) {\n\tlines(x = temp_range, y = mu[, i], col = col.alpha(\"black\", 0.05))\n}\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n\nYeah, the default priors look pretty good to me. The only change I made was to increase the width of the prior for $w$, to potentially allow for more wiggliness. There is a bit of wiggling out of the expected day of year range, but it's so rare that I think it will be fine, especially after the model sees the data. I think it will be harder to set the correct prior on $w$ with a prior predictive simulation, so I think we better go ahead and fit the model.\n\nNow let's fit a `quap` model. Note that I had to turn up the maximum number of iterations run by the underlying `optim` call to ensure convergence criteria were met.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the real splines\nB_real <-\n\tsplines::bs(\n\t\tx = d2$temp,\n\t\tknots = quantile(temp_range, probs = seq(0, 1, length.out = nk))[-c(1, nk)],\n\t\tdegree = 3,\n\t\tintercept = TRUE\n\t)\n\n# Fit the model\nm4h6 <-\n\tquap(\n\t\tflist = alist(\n\t\t\tD ~ dnorm(mu, sigma),\n\t\t\tmu <- a + B %*% w,\n\t\t\ta ~ dnorm(100, 10),\n\t\t\tw ~ dnorm(0, 15),\n\t\t\tsigma ~ dexp(1)\n\t\t),\n\t\tdata = list(D = d2$doy, B = B_real),\n\t\tstart = list(w = rep(0, ncol(B_real))),\n\t\tcontrol = list(maxit = 200)\n\t)\n\nrethinking::precis(m4h6, depth = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             mean         sd       5.5%      94.5%\nw[1]    0.0000000 14.9999514 -23.972819  23.972819\nw[2]    0.0000000 14.9999514 -23.972819  23.972819\nw[3]    0.0000000 14.9999514 -23.972819  23.972819\nw[4]    6.9549283  5.2048778  -1.363472  15.273328\nw[5]    4.7825332  4.8284596  -2.934278  12.499344\nw[6]    5.3724394  4.7117796  -2.157895  12.902773\nw[7]    1.1616676  4.6557218  -6.279075   8.602410\nw[8]   -0.1986208  4.8130958  -7.890877   7.493636\nw[9]   -3.4414421  5.1367824 -11.651012   4.768128\nw[10]  -2.3424900  5.7891404 -11.594655   6.909674\nw[11]  -6.1560988  7.2908763 -17.808327   5.496130\nw[12]  -0.4530242  6.7393765 -11.223849  10.317801\nw[13]   0.0000000 14.9999514 -23.972819  23.972819\nw[14]   0.0000000 14.9999514 -23.972819  23.972819\nw[15]   0.0000000 14.9999514 -23.972819  23.972819\nw[16]   0.0000000 14.9999514 -23.972819  23.972819\nw[17]   0.0000000 14.9999514 -23.972819  23.972819\na     102.5223225  4.5314729  95.280154 109.764491\nsigma   5.8829498  0.1474653   5.647272   6.118628\n```\n\n\n:::\n:::\n\n\n\n\nAlright, now we can get the actual predictions and plot them.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(d2$doy ~ d2$temp, xlab = \"Temperature (Celsius)\", ylab = \"Day of year\",\n\t\t col = col.alpha(rangi2, 0.4), pch = 16)\n\n# Get the predictions and interval -- have to use the basis over the\n# interpolated temperature data!\nlink_m4h6 <- link(m4h6, data = list(B = B))\nmu <- apply(link_m4h6, 2, mean)\nmu_pi1 <- apply(link_m4h6, 2, PI, 0.97)\nmu_pi2 <- apply(link_m4h6, 2, PI, 0.89)\nmu_pi3 <- apply(link_m4h6, 2, PI, 0.61)\n\n# lines(temp_range, mu_pi3[1, ], lty = 2)\n# lines(temp_range, mu_pi3[2, ], lty = 2)\n# lines(temp_range, mu_pi2[1, ], lty = 2)\n# lines(temp_range, mu_pi2[2, ], lty = 2)\n# lines(temp_range, mu_pi1[1, ], lty = 2)\n# lines(temp_range, mu_pi1[2, ], lty = 2)\nshade(mu_pi1, temp_range, col = col.alpha(\"black\", 0.5))\nshade(mu_pi2, temp_range, col = col.alpha(\"darkgray\", 0.5))\nshade(mu_pi3, temp_range, col = col.alpha(\"gray\", 0.5))\nlines(temp_range, mu, lty = 2, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\nOK, so I had some confusion here with plotting the predictions. I forgot that I need to specify a separate $B$ matrix of basis functions for the model fitting and for this part of the predictions. But now it is working and we can see that there is definitely a decent association between warmer temperatures and earlier blooming. However, we would need more high-temperature data to confirm this trend (and high-temperature data is something we wish we didn't have more of, really).\n\n### 4H6\n\n**Q.** Simulate the prior predictive distirbution for the cherry blossom spline in the chapter. Adjust the prior on the weights and observe what happens. What do you think the prior on the weights is doing?\n\nOk, first we need to simulate the PPD. I'm pretty sure I already have a handle on this from the previous two spline exercises, but it should be fun. (In fact, we really already did this exact exercise, but whatever I guess.)\n\nLet's simulate with maybe six different widths: 1, 5, 10 (chosen in the textbook), 15, 20, and 50. I'll get the predictions from each of these simulations and then plot them.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get ready for simulation.\n# Set parameters for sim\nwidths <- c(1, 5, 10, 15, 20, 50)\nN <- 250\nset.seed(100)\nlayout(matrix(c(1, 2, 3, 4, 5, 6), ncol = 3, nrow = 2))\n\n# Create the splits\nnk <- 15\nyear_range <- seq(800, 2010, 1)\nknot_list <- quantile(year_range, probs = seq(0, 1, length.out = nk))\nB <- splines::bs(\n\t\t\t\tx = year_range,\n\t\t\t\t# I think we are recreating the default knots and could set\n\t\t\t\t# df = 13 instead, but nonetheless we persist\n\t\t\t\tknots = knot_list[-c(1, nk)],\n\t\t\t\tdegree = 3,\n\t\t\t\tintercept = TRUE\n\t\t\t)\n\nsim_res <- vector(mode = \"list\", length = length(widths))\n\ndo_pps <- function(width) {\n\t# Simulate a since it is easy\n\ta <- rnorm(N, 100, 10)\n\t\n\t# Simulate the weights with a little trickery\n\tw <- do.call(rbind, purrr::map(1:ncol(B), ~rnorm(N, 0, width)))\n\t\n\t# Calculate the predicted means\n\tmu <- a + B %*% w\n\t\n\tplot(\n\t\tNULL,\n\t\txlim = c(800, 2010), ylim = c(40, 170),\n\t\txlab = \"year\", ylab = \"day of year\",\n\t\txaxs=\"i\", yaxs=\"i\",\n\t\tmain = paste(\"Width:\", width)\n\t)\n\t\n\tfor (i in 1:N) {\n\t\tlines(x = year_range, y = mu[, i], col = col.alpha(\"black\", 0.01))\n\t}\n\t\t\n\tabline(h =  60, lty = 2, lwd = 0.5)\n\tabline(h = 152, lty = 2, lwd = 0.5)\n\t\n\treturn(NULL)\n}\n\nout <- sapply(widths, do_pps)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\nYep, just like I said in the other two exercises about this, the width of the spline prior determines the amount of smoothness that the spline should have. If we increase the width, the spline is encouraged to vary more, and will \"wiggle\" (spike up and down) with larger fluctuations. If we constrain this parameter, the spline is encouraged to vary less, staying closer to the intercept.\n\n### 4H8\n\n**Q.** The cherry blossom split in the chapter used an intercept $\\alpha$, but technically it doesn't require one. The first basis functions could substitute for the intercept. Try refitting the cherry blossom spline without the intercept. What else about the model do you need to change to make this work.\n\nThis question is worded a bit confusingly to me. I assume he means the intercept parameter in the model, because the basis splines have a separate intercept that we also set to be true. Either way, let's go ahead and try refitting a model without the intercept.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data import\ndata(\"cherry_blossoms\")\nd <- cherry_blossoms\nd2 <- d[complete.cases(d$doy), ]\n\nset.seed(100)\n# Create the splits\nnk <- 15\nknot_list <- quantile(d2$year, probs = seq(0, 1, length.out = nk))\nB <- splines::bs(\n\t\t\t\tx = d2$year,\n\t\t\t\t# I think we are recreating the default knots and could set\n\t\t\t\t# df = 13 instead, but nonetheless we persist\n\t\t\t\tknots = knot_list[-c(1, nk)],\n\t\t\t\tdegree = 3,\n\t\t\t\tintercept = TRUE\n\t\t\t)\n\n# Fit the model\nm <-\n\tquap(\n\t\tflist = alist(\n\t\t\tD ~ dnorm(mu, sigma),\n\t\t\tmu <- B %*% w,\n\t\t\tw ~ dnorm(0, 10),\n\t\t\tsigma ~ dexp(1)\n\t\t),\n\t\tdata = list(D = d2$doy,\tB = B),\n\t\tstart = list(w = rep(0, ncol(B)))\n\t)\n\n# Get the posterior predictions and plot them\nmu <- link(m)\nmu_PI <- apply(mu, 2, PI, 0.97)\n\nlayout(1)\nplot(d2$year, d2$doy, col = col.alpha(rangi2, 0.3), pch = 16,\n\t\t xlab = \"year\", ylab = \"Day in year\")\nshade(mu_PI, d2$year, col = col.alpha(\"darkgray\", 0.5))\nlines(d2$year, y = apply(mu, 2, mean), col = \"red\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\nWell, I'll be honest. I'm not really sure what else we're supposed to change here because that model looks perfectly fine to me. It has some curvature at the lowest year values though, which we maybe should have expected since we basically set the intercept to zero. I think we could improve this by adjusting the prior for $w$ to have a mean that was the same mean as the previous intercept prior (that is, 100). Maybe that's the other thing we need to change. Let's try it.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Save the previous results or whatever\nold_mu <- mu\nold_mu_PI <- mu_PI\n\n# Fit the model\nm <-\n\tquap(\n\t\tflist = alist(\n\t\t\tD ~ dnorm(mu, sigma),\n\t\t\tmu <- B %*% w,\n\t\t\tw ~ dnorm(100, 10),\n\t\t\tsigma ~ dexp(1)\n\t\t),\n\t\tdata = list(D = d2$doy,\tB = B),\n\t\tstart = list(w = rep(0, ncol(B)))\n\t)\n\n# Model with intercept\nma <-\n\t\tquap(\n\t\tflist = alist(\n\t\t\tD ~ dnorm(mu, sigma),\n\t\t\tmu <- a + B %*% w,\n\t\t\ta ~ dnorm(100, 10),\n\t\t\tw ~ dnorm(0, 10),\n\t\t\tsigma ~ dexp(1)\n\t\t),\n\t\tdata = list(D = d2$doy,\tB = B),\n\t\tstart = list(w = rep(0, ncol(B)))\n\t)\n\na_mu <- link(m)\na_mu_PI <- apply(mu, 2, PI, 0.97)\n\n\n# Get the posterior predictions and plot them\nmu <- link(m)\nmu_PI <- apply(mu, 2, PI, 0.97)\n\n# Plot the results with both lines\nplot(d2$year, d2$doy, col = col.alpha(rangi2, 0.3), pch = 16,\n\t\t xlab = \"year\", ylab = \"Day in year\")\nlines(d2$year, y = apply(a_mu, 2, mean), col = \"green\", lty = 2)\nlines(d2$year, y = apply(old_mu, 2, mean), col = \"blue\", lty = 2)\nlines(d2$year, y = apply(mu, 2, mean), col = \"red\", lty = 2)\nlegend(\n\tx = \"top\",\n\tlegend = c(\"intercept\", \"no intercept mean 0\", \"no intercept mean 100\"),\n\tlty = c(2, 2, 2),\n\tcol = c(\"green\", \"blue\", \"red\")\n)\n```\n\n::: {.cell-output-display}\n![](cp4_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n\nYes indeed, if you look closely, you can see that the red line and the green line are almost exactly the same. Which means that if we adjust the mean of the spline prior, we can fit the exact same model without an intercept. Yay.\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "cp4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}