{
  "hash": "b60052faeb7380d664f3b8edb5745cc8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Chapter 13: The Tools of Parameter Estimation\"\ndraft: false\n---\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(\"scipen\" = 9999, \"digits\" = 4)\n```\n:::\n\n\n\n* This chapter covers using the PDF, CDF, and quantiles for distributions.\n* Notably, the book explains that they use the word \"confidence interval\" when\nthey are actually talking about Bayesian credible intervals -- there is really\nno reason for them to do this and it is confusing.\n\n## Q1\n\n::: {.callout-note appearance=\"simple\"}\n\nUsing the code example for plotting the PDF on page 127, plot the CDF and\nquantile functions.\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxs <- seq(0.005, 0.01, by = 1e-5)\nplot(\n\txs,\n\tpbeta(xs, 300, 4e4 - 300),\n\ttype = \"l\", lwd = 3,\n\txlab = \"Probability of subscription\",\n\tylab = \"Cumulative probability\",\n\tmain = \"CDF Beta(300, 39700)\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Q1 CDF plot-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nxs <- seq(1e-5, 1 - 1e-5, 1e-5)\nplot(\n\txs,\n\tqbeta(xs, 300, 4e4 - 300),\n\ttype = \"l\", lwd = 3,\n\tylab = \"Probability of subscription\",\n\txlab = \"Cumulative probability\",\n\tmain = \"Quantile function Beta(300, 39700)\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Q1 quantile plot-1.png){width=672}\n:::\n:::\n\n\n\n## Q2\n\n::: {.callout-note appearance=\"simple\"}\n\nReturning to the task of measuring snowfall from Chapter 10, say you have the\nfollowing measurements (in inches) of snowfall:\n\n> `7.8, 9.4, 10.0, 7.9, 9.4, 7.0, 7.0, 7.1, 8.9, 7.4`.\n\nWhat is your 99.9% confidence interval for the true value of snowfall?\n\n:::\n\nAssuming the snowfall measurements are normally distributed, first we need\nto calculate the mean and standard deviation of the measurements.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnow <- c(7.8, 9.4, 10.0, 7.9, 9.4, 7.0, 7.0, 7.1, 8.9, 7.4)\n(snow_mean <- mean(snow))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.19\n```\n\n\n:::\n\n```{.r .cell-code}\n(snow_sd <- sd(snow))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.135\n```\n\n\n:::\n:::\n\n\n\nNow to obtain a $99.9\\%$ credible interval, we need to calculate quantiles where\nthe probabilities are $0.0005$ and $0.9995$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(snow_ci <- qnorm(c(0.0005, 0.9995), snow_mean, snow_sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  4.456 11.924\n```\n\n\n:::\n:::\n\n\n\nSo our estimate for the actual snowfall is 8.19 inches with\na $99.9\\%$ credible interval of\n$(4.46, 11.92)$.\n\n## Q3\n\n::: {.callout-note appearance=\"simple\"}\n\nA child is going door to door selling candy bars. So far she has visited 30\nhouses and sold 10 candy bars. She will visit 40 more houses today. What is the\n95% confidence interval for how many candy bars she will sell the rest of the\nday?\n\n:::\n\nWe'll model the probability, say $\\pi$ that a house will buy chocolate bars\nusing a beta distribution. Based on the information we have so far, we should\nassume that\n$$\\pi \\sim \\mathcal{B}(10, 20).$$\n\n\nWe can then calculate the mean and the 95% confidence interval using the\ndistribution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(mean_pi <- 10 / 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3333\n```\n\n\n:::\n\n```{.r .cell-code}\n(ci_pi <- qbeta(c(0.025, 0.975), 10, 20))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1794 0.5083\n```\n\n\n:::\n:::\n\n\n\nSo, if she visits 40 more houses today, we can calculate the number of houses\nwe expect to buy chocolate for each of those probability estimates.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(mean_choc <- mean_pi * 40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.33\n```\n\n\n:::\n\n```{.r .cell-code}\n(ci_choc <- ci_pi * 40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  7.175 20.333\n```\n\n\n:::\n:::\n\n\n\nSo we would expect $13$ houses to buy chocolate if the trend\nstays the same, with a $95\\%$ credible interval of $(7,\n21)$. (Note that the interval is not exact due to rounding,\nbut it is the closest we can get with integer boundaries.)\n\nWe can also make a plot of the expected number of chocolate bars.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxs <- seq(1e-5, 1 - 1e-5, 1e-5)\nplot(\n\tNULL, NULL,\n\tylab = \"Probability of selling at least this many chocolate bars\",\n\txlab = \"Number of chocolate bars\",\n\tmain = \"CCDF Beta(10, 20) * 40\",\n\txlim = c(0, 40),\n\tylim = c(0, 1),\n\taxes = FALSE\n)\n\nabline(v = floor(mean_choc), lty = 2, lwd = 2)\nabline(v = floor(ci_choc[[1]]), lty = 3, lwd = 1.5)\nabline(v = ceiling(ci_choc[[2]]), lty = 3, lwd = 1.5)\nlines(\n\txs * 40,\n\t1 - pbeta(xs, 10, 20),\n\ttype = \"l\", lwd = 3\n)\naxis(\n\t1,\n\tat = c(seq(0, 40, 10), floor(mean_choc), floor(ci_choc[[1]]),\n\t\t\t\t ceiling(ci_choc[[2]]))\n)\naxis(2, at = seq(0, 1, 0.25))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/q3 beta plot-1.png){width=672}\n:::\n:::\n\n\n\n\n<!-- END OF FILE -->\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}