{
  "hash": "03739d773565579a9345dc95c4aacca5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Chapter 12: The Normal Distribution\"\ndraft: false\n---\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(\"scipen\" = 9999, \"digits\" = 4)\n```\n:::\n\n\n\nThis chapter introduces the normal distribution. There's not much else to\nsay about it.\n\n## Q1\n\n::: {.callout-note appearance=\"simple\"}\n\nWhat is the probability of observing a value five sigma greater than the mean\nor more?\n\n:::\n\nSince we know that this property is invariant for all normal family\ndistributions, we can estimate it numerically using a standard normal\ndistribution, for which the standard deviation is 1. Therefore, we can estimate\nthe probability of interest by calculating\n$$P(x \\geq 5) = \\int_{5}^{\\infty} \\mathcal{N}(0, 1) \\ \\mathrm{d}x,$$\nwhich is easy to approximate in\nR.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob <- integrate(\\(x) dnorm(x), 5, Inf)$value\nprint(prob)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0000002867\n```\n\n\n:::\n:::\n\n\n\nThe probability is 0.0000002867, which is quite low,\nless than a hundred-thousandth of a percent.\n\n## Q2\n\n::: {.callout-note appearance=\"simple\"}\n\nA fever is any temperature greater than 100.4 degrees Fahrenheit. Given the\nfollowing measurements, what is the probability that the patient has a fever?\n\n> `100.0, 98.8, 101.0, 100.5, 99.7`\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemps <- c(100.0, 98.8, 101.0, 100.5, 99.7)\n(temp_mean <- mean(temps))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n\n```{.r .cell-code}\n(temp_sd <- sd(temps))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8337\n```\n\n\n:::\n:::\n\n\n\n\nAssuming the temperature measurements have normally distributed error away\nfrom the true underlying temperature value (which we assume is constant),\nwe can estimate the mean as 100 degrees and the standard\ndeviation as 0.83. Then, the probability that the patient has\na fever is\n$$ P(\\text{temp} \\geq 100.4) = \\int_{100.4}^{\\infty} \\mathcal{N}(100, 0.83) \\ \\mathrm{d} (\\text{temp}).$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfever_prob <- integrate(\\(x) dnorm(x, temp_mean, temp_sd), 100.4, Inf)\nprint(fever_prob)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.3157 with absolute error < 0.0000009\n```\n\n\n:::\n:::\n\n\n\nGiven all of our assumptions and measurements, the probability that the patient\nhas a fever is about 31.57 percent.\n\n\n## Q3\n\n::: {.callout-note appearance=\"simple\"}\n\nSuppose in Chapter 11 we tried to measure the depth of a well by timing coin\ndrops and we got the following values:\n\n> `2.5, 3.0, 3.5, 4.0, 2.0`.\n\nThe distance an object falls can be calculated (in meters) with the formula\n$$\\text{distance} = \\frac{1}{2}\\times G \\times \\text{time}^2$$\nwhere $G = 9.8 \\ \\text{m}/\\text{s}^2,$ the gravitational constant. What is the\nprobability that the well is over 500 meters deep?\n\n:::\n\nFirst, we need to calculate the fall distances we would have gotten from\nthese times.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntimes <- c(2.5, 3.0, 3.5, 4.0, 2.0)\ndistances <- 0.5 * 9.8 * times ^ 2\nknitr::kable(data.frame(\"t\" = times, \"d\" = distances))\n```\n\n::: {.cell-output-display}\n\n\n|   t|     d|\n|---:|-----:|\n| 2.5| 30.62|\n| 3.0| 44.10|\n| 3.5| 60.02|\n| 4.0| 78.40|\n| 2.0| 19.60|\n\n\n:::\n:::\n\n\n\nNow, assuming that the errors in measuring the distance are normally\ndistributed, we can calculate the mean and standard deviation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(dist_mean <- mean(distances))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 46.55\n```\n\n\n:::\n\n```{.r .cell-code}\n(dist_sd <- sd(distances))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.36\n```\n\n\n:::\n:::\n\n\n\nFinally, we compute the probability by integrating from 500 to infinity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_500_depth <- integrate(\\(x) dnorm(x, dist_mean, dist_sd), 500, Inf)\nprint(prob_500_depth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.000000000000000000000000000000000000000000000000000000000000000000000000000000000002872 with absolute error < 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000034\n```\n\n\n:::\n:::\n\n\n\nThe probability might as well be 0, it's actually somewhere around $10 ^ {-83.54}$.\n\n\n## Q4\n\n::: {.callout-note appearance=\"simple\"}\n\nWhat is the probability there is no well (i.e. the well is really 0 meters\ndeep)? You'll notice that probability is higher than you might expect, given\nyour observation is that there *is* a well. There are two good explanations for\nthis probability being higher than it should. The first is that the normal\ndistribution is a poor model for our measurements, the second is that, when\nmaking up numbers for an example, I chose values that you likely wouldn't see\nin real life. Which is more likely to you?\n\n:::\n\nThe question is ill-posed. The probability that the depth of the well is 0\nmeters is 0, because the probability of any single point is 0, since we've\nassumed a continuous distribution for the measurements. We have to approximate\nthe probability by finding the probability of a small neighborhood around zero,\nwhich is similar but not quite the same thing. If we instead interpret the\nquestion to mean the depth of the well is *zero or less*, we can integrate\nfrom -infinity to zero.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob_0_depth <- integrate(\\(x) dnorm(x, dist_mean, dist_sd), -Inf, 0)\nprint(prob_0_depth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.02312 with absolute error < 0.0000028\n```\n\n\n:::\n:::\n\n\n\nAccording to our model, there is almost a $2.31 \\%$\nchance that the well has a zero or negative depth! Which clearly doesn't make sense.\nNotably, in the official solution, the author models the times instead of the\ndistances, but also gets a nonsensical result.\n\nClearly, a normal distribution is not appropriate here. Neither times nor\ndistances can be negative, and yet using a normal distribution for either\ngives positive probabilities of negative results. Furthermore, the data are\nincredibly spread out on the distance scale, implying that our measurements\nare not very good. So both problems are true.\n\nThe official solution claims that there is \"no reason to question the\nassumptions of the normal distribution here\", but that is an obviously\nuntrue statement.\n\n<!-- END OF FILE -->\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}