---
title: "Chapter 4"
author: "Zane Billings"
date: "2022-12-09"
draft: true
---

```{r setup}
options("scipen" = 9999, "digits" = 16)
```


## Q1

::: {.callout-note appearance="simple"}

What are the parameters of the binomial distribution for the probability of
rolling either a 1 or a 20 on a 20-sided die, if we roll the die 12 times?

:::

The parameters are $n = 12$ and $p = 2/20 = 1/10 = 0.1$.

## Q2

::: {.callout-note appearance="simple"}

There are four aces in a deck of 52 cards. If you pull a card, return the card, then reshuffle, and pull a card again, how many ways can you pull just one ace in 
five pulls?

:::




## Q3

::: {.callout-note appearance="simple"}

For the example in question 2, what is the probability of pulling 5 aces in
10 pulls (remember the card is shuffled back in the deck when it is pulled)?

:::

## Q4

::: {.callout-note appearance="simple"}

When you're searching for a new job, it's always helpful to have more than one offer on the table so you can use it in negotiations. If you have a 1/5 probability
of recieving a job offer when you interview, and you interview with seven
companies in a month, what is the probability you'll have at least two
competing offers by the end of that month.

:::

## Q5

::: {.callout-note appearance = "simple"}

You get a bunch of recruiter emails and find out you have 25 interviews lined up
in the next month. Unfortunately, you know that this will leave you exhausted,
and the probability of getting an offer will drop to 1/10 if you're tired.
You really don't want to go on this many interviews unless you are at least
twice as likely to get at least two competing offers. Are you more likely to
get at least two offers if you go for 25 interviews, or stick to just 7?

:::

<!-- end of file -->
