---
format: gfm
---

<!-- README.md is generated from README.qmd. Please edit that file! -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-",
  fig.retina = 3
)

# Updated versions of the mime and markdown packages are needed to knit
# quarto documents, but this are not formal dependencies linked to renv.
# So I'll require them here to make them formal dependencies.
box::use(
	mime,
	markdown,
	rmarkdown
)
```

# Bookwork: Exercises and Solutions

This website contains my notes, solutions, etc. for a few textbooks I've read.
I'm partially trying to document my learning and thinking process for myself so
I can come back to it later if I need to, but also partially trying to write the
solutions in an expository style so they can be understood by other people who
happen to read this.

## Current books

* **Bayesian Statistics the Fun Way** by [Will Kurt](https://www.countbayesie.com/about).
* **Statistical Rethinking**, 2nd edition, by [Richard McElreath](https://xcelab.net/rm/).

## Bug and typo reports

* [GH Issues](https://github.com/wzbillings/bookwork/issues) for questions or typos
or comments or things that I said that are incorrect are welcome!
* Since this repo is for my personal work on textbook studying, I don't plan
to accept contributions at this time. However, PRs for typos, etc. are appreciated.

## Reuse

* All materials from textbooks do not belong to me and are included under fair
use for educational purposes.
* Any original text or images I create are licensed under the
[Creative Commons BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)
license.
* Any original code that I write is licensed under the
[GNU AGPL 3.0 license](https://www.gnu.org/licenses/agpl-3.0.en.html).
* All `R` code and any packages that were not created by me are subject to
their original licensing.

<!-- END OF FILE -->
